# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WakeupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('arrival_time', models.TimeField()),
                ('breakfast_time', models.TimeField()),
                ('wakeup_time', models.TimeField()),
            ],
        ),
    ]
